### PR TITLE
Fixed failing its.

### PR DESCRIPTION
**Pull request by akuhtz**
This fixes IT failures.

### CODE REVIEW

**Comment by khmarbaise** [comment]
Maybe I misunderstand the intention of your pull request but the buildnumber-maven-plugin has already a dependency to svnkit...currently 1.8.12 on master ...?

**Comment by akuhtz** [comment]
Hi,
You're right :-( 
I didn't see it and copied the dependency from another IT to get it pass locally but it only needs the providerImplementation set to javasvn to pass if no native svn implementation is on the path as it was in my case.
I changed svnkit from 1.8.12 back to 1.8.3-1 after the CI build failed ...

Now I just added a native svn implementation to the path and now the original tests pass. I'll close the PR and sorry for the noise.

**Comment by khmarbaise** [comment]
please don`t be sorry for trying to help...and it's great that you found an issue...please create an issue for your improvement to make these IT's independent of the installation of SVN...and create an pull request for that...I appreciate to merge that...

**Comment by akuhtz** [comment]
I'll open a new PR with the fix for the ITs.

**Pull request closed without merging**
