### PR TITLE
Update HgChangeSetMojo.java

### PR DESCRIPTION
**Pull request by preafos**
Added constant String variables for every property and added support for the locale revision number now stored as "localeRevisionNumber" property.

### CODE REVIEW

**Comment by khmarbaise** [comment]
The pull requests look good so far. Could you please squash your commits into a single one and include a commit comment like this:
```
Fixed #63
 o Including the locale revision number for the goal hgchangeset 
```
That will automatically close the appropriate issue if it will be merged to master.

**Comment by preafos** [comment]
With squash you mean: creating a new pull request with one commit and the comment underneath?On 16 Jun 2017 11:11 am, Karl Heinz Marbaise <notifications@github.com> wrote:The pull requests look good so far. Could you please squash your commits into a single one and include a commit comment like this:
Fixed #63
 o Including the locale revision number for the goal hgchangeset 

That will automatically close the appropriate issue if it will be merged to master.

**Comment by khmarbaise** [comment]
It is not needed to make a new PR you can squash your commits on the branch (patch-2) you have created them (git rebase -i HEAD~2) and make a `git push origin --force-with-lease patch-2 ` than they will come here to the same PR...but with a singe commit...which makes it easier to integrate the change.

**Comment by preafos** [comment]
OK, unfortunately I created these Patches though github. For the moment I don't have a clue how to do this through this ui.

**Comment by khmarbaise** [comment]
I can't tell you if this possible via ui I use git only from command line...But of course you can take your time...I would like to integrate your contribution...

**Pull request closed without merging**
