### PR TITLE
Support getting branch info from Mercurial (Hg)

### PR DESCRIPTION
**Pull request by codingtony**
Added support to get branch info from Hg.

### CODE REVIEW

**Comment by sreich** [comment]
could we please get this merged? (and #10 )

and a new release performed would be nice..we need this feature pretty badly at work. last release was april 2014..

**Comment by abelyakov** [comment]
Also wait for this pull.

**Comment by codingtony** [comment]
Is there someone watching this issue?

**Comment by codingtony** [comment]
https://github.com/mojohaus/buildnumber-maven-plugin/pull/10  is achieving the same thing, so please pull either one

**Comment by Jamuz** [comment]
Anyone watching this? Could someone please merge and release?

**Pull request merged**
