### PR TITLE
Avoid "The scm url cannot be null" error with available ".git" metadata.

### PR DESCRIPTION
**Pull request by sjoerdtalsma**
In this case a local file URL is used as SCM url as fallback if none was declared in the maven pom.

There are more people that have encountered this issue, so presumably there's a broader demand for this, hence my pull-request:
https://www.google.com/search?q=buildnumber-maven-plugin+The+scm+url+cannot+be+null

By the way; I couldn't run all integration tests (because I don't have other SCM systems installed locally?)

### CODE REVIEW

**Comment by sjoerdtalsma** [comment]
@olamy or @dantran Could someone 'senior' on the buildnumber-maven-plugin please review this PR or comment whether or not it's something we want?

**Comment by sjoerdtalsma** [comment]
...anyone? @khmarbaise maybe?

**Comment by sjoerdtalsma** [comment]
@rfscholte Is this project still maintained at all?

**Comment by rfscholte** [comment]
In general Mojohaus is still active, but I don't even have enough time to work on Apache Maven itself, hence I rarely work on Mojohaus.

**Comment by sjoerdtalsma** [comment]
@rfscholte 
> In general Mojohaus is still active, but I don't even have enough time to work on Apache Maven itself, hence I rarely work on Mojohaus.

Robert, first of all thanks for the quick reply! I was not expecting you to handle this pull-request personally. But on a meta-level, is it too much to ask for a review for a small fix like this within 16 months? I realise it's mostly volunteer work, but outside contributors are bound to leave frustrated if the maintainers don't merge (or at least review) contributions in a timely fashion.

**Comment by dantran** [comment]
not possible to review when you format the code, and change also not follow mojohaus/maven format convention. 

Need a test case

**Comment by sjoerdtalsma** [comment]
@dantran Thanks for a reaction
> not possible to review when you format the code
I see only my change perfectly in this PR so I have not formatted any other code according to github

> and the hanges also not follow mojohaus/maven format convention
Please point out the problems and I'll be happy to update the code. I was under the impression I followed the conventions I found already there.

> Need a test case
Thanks for the feedback, I'll see what I can do although I currently cannot run _all_ it tests locally.

**Comment by dantran** [comment]
here is maven/mojohaus coding convention: https://maven.apache.org/developers/conventions/code.html

Best practice would be to delay code format in a separate PR

**Pull request closed without merging**
